version: "3.1"

services:
  pingdirectory:
    image: pingidentity/pingdirectory:edge
    environment:
      - SERVER_PROFILE_URL=https://github.com/gmorgan-ping/pingidentity-server-profiles.git
      - SERVER_PROFILE_PATH=baseline/pingdirectory
      - PING_IDENTITY_ACCEPT_EULA=YES
      - PING_IDENTITY_DEVOPS_USER=${PING_IDENTITY_DEVOPS_USER}
      - PING_IDENTITY_DEVOPS_KEY=${PING_IDENTITY_DEVOPS_KEY}
    ports:
      - 1636:636
      - 1443:443
    networks:
      - pingnet
                    
  pingdataconsole:
    image: pingidentity/pingdataconsole:edge
    ports:
      - 8443:8443
    networks:
      - pingnet

networks:
    pingnet:
